- name: Installing the nginx package
  ansible.builtin.package:
    name: nginx
    state: present
- name: starting the nginx package
  ansible.builtin.package:
    name: nginx
    state: started

- name: download the frontend content
  ansible.builtin.unarchive:
    src: https://github.com/stans-robot-project/frontend/archive/main.zip
    dest: /tmp/frontend.zip
    remote_src: yes

- name: Removing the directory from nginx folder
  ansible.builtin.file:
     path: /usr/share/nginx/html
     state: absent

- name: Unarchive a file in remote machine
  ansible.builtin.unarchive:
    src: /tmp/frontend.zip
    dest: /usr/share/nginx/html
    remote_src: yes

- name: moving file
  ansible.builtin.shell:
   - mv /usr/share/nginx/html/frontend-main/* /usr/share/nginx/html
  remote_src: yes

- name: moving file
  ansible.builtin.shell:
    - mv /usr/share/nginx/html/static/* /usr/share/nginx/html
  remote_src: yes
  
- name: Removing the directory from frontend-main folder
  ansible.builtin.file:
     path: /usr/share/nginx/html/frontend-main
     state: absent


- name: restarting the nginx package
  ansible.builtin.package:
    name: nginx
    state: started


  