#Creating Variables
- name: Create variable
  hosts: all
  vars_files:
    - Variable-File.yaml
  tasks:
    - name: first variable creation
      ansible.builtin.debug:
       msg: Printing {{ Test }} variable
    - name: print only variable
      ansible.builtin.debug:
       msg: "{{ Test }}"
      vars:                            # task-level / local variables 
        Test: task.google.com   