#Creating Variables
- name: Create variable
  hosts: all
  vars:
   Test: Hari
  tasks:
    - name: first variable creation
      ansible.builtin.debug:
       msg: Printing {{ Test }} variable
    - name: print only variable
      ansible.builtin.debug:
       msg: "{{ test }}"
      vars:                            # task-level / local variables 
        URL: task.google.com   