
- name: working on ignore method
  hosts: dev
  tasks:
   - name: using shell to print errors
     ansible.builtin.shell: pf -ef | grep java
     register1: checkerror
   - name: using debug method for Printing
     ansible.builtin.debug:
       msg: "checkerror"