...
-name: Printing uptime of dev machine
  hosts: Dev
  #become: true
  tasks:
   - name: using script method for retriving the data
     ansible.builtin.shell: uptime
     register: Devmachine
   - name: using debug method for Printing
     ansible.builtin.debug:
       msg: "Devmachine"  
...

- name: working on ignore method
  hosts: dev
  tasks:
   - name: using shell to print errors
     ansible.builtin.shell: pf -ef | grep java
     register1: checkerror
   - name: using debug method for Printing
     ansible.builtin.debug:
       msg: "checkerror"