#Creating Variables

- name: printing the machine name for ansible playbook
  hosts: all
  tasks:
  ansible.builtin.debug:
   msg: print machine names {{ id }}

- name: creating variable for the asible playbook
  hosts: all
  tasks:
  vars:
   URL: gmail.google.com
  ansible.builtin.debug:
   msg: "{{ URL }}"  